#!/usr/bin/php
<?php

use React\EventLoop\Factory,
    React\Http\Server,
    React\Http\Response,
    React\Socket\Server as HttpSocketServer,
    React\Cache\ArrayCache,
    WyriHaximus\React\Http\Middleware\SessionMiddleware,
    WyriHaximus\React\Http\Middleware\WebrootPreloadMiddleware;

#
# Config
#
if(file_exists(dirname(__DIR__).'/config.json')) {
    $config = json_decode(file_get_contents(dirname(__DIR__).'/config.json'), true);
    foreach($config as $key => $value) define($key, $value);
} else die('Config file not found');

require dirname(__DIR__).'/vendor/autoload.php';
require dirname(__DIR__).'/src/routes.php';

//Database connection booting
Models\Database::boot();

#
# Run the server
#
$loop = Factory::create();

$server = new Server([
    new SessionMiddleware(
        CONF_COOKIE_NAME,
        new ArrayCache()
    ),

    new WebrootPreloadMiddleware(
        dirname(__DIR__).'/public'
    ),

    /**
     * @todo Cesi user middleware role unauthorized pages (403)
     */

    function($request) use(&$router) {

        $response = new Response(
            200,
            array(
                'Content-Type' => 'text/html',
                'X-Powered-By' => 'PHP/'.phpversion()
            )
        );

        try {
            //Match HTTP request
            return $router->run($request, $response);
        } catch(Throwable $e) {
            //Error 500 handling
            $errstr = '« '.$e->getMessage().' » in '.$e->getFile().' line '.$e->getLine();
            echo $errstr;
            return Controllers\ErrorController::error500($request, $response, $errstr);
        }

    }

    /**
     * @todo logs http access middleware
     */
]);

$socket = new HttpSocketServer(CONF_PORT_SERVER, $loop);
$server->listen($socket);
echo date('d/m H:i:s : '), "server running at http://127.0.0.1:".CONF_PORT_SERVER."\n";

$loop->run();